Map<int, String> servicesEng = {
  0: "Oclif",
  1: "SERVICE",
  2: "SUBMIT",
  3: "Language",
  4: "Preferred Language",
  5: "Select Preferred Language",
  6: "Home",
  7: "Chat",
  8: "Booking",
  9: "Account",
  10: "Change Language",
  11: "Set your Preferred language",
  12: "Enable Dark Mode",
  13: "Set you favorite mode",
  14: "Privacy Policy",
  15: "Known our Privacy Policy",
  16: "View profile",
  17: "Log Out",
  18: "End the session",
  19: "Notifications",
  20: "Lots of important information",
  21: "Name",
  22: "Enter your name",
  23: "Email",
  24: "Enter your Email",
  25: "Phone number",
  26: "Enter your Phone number",
  27: "Address",
  28: "Enter address for customers",
  29: "Description",
  30: "Enter Short description about you",
  31: "SAVE",
  32: "Change password",
  33: "New password",
  34: "Enter Password",
  35: "Confirm New password",
  36: "Enter Password",
  37: "CHANGE PASSWORD",
  38: "My Profile",
  39: "Everything about you",
  40: "reviews",
  41: "Read all",
  42: "Average Ratings",
  43: "Sign in now",
  44: "Password",
  45: "Enter your Password",
  46: "CONTINUE",
  47: "REGISTER",
  48: "or continue with",
  49: "Register",
  50: "in less than a minute",
  51: "Confirm Password",
  52: "Verification",
  53: "We'll sent verification code.",
  54: "We've sent 6 digit verification code.",
  55: "Enter code",
  56: "Enter 6 digits code",
  57: "Write your message ...",
  58: "New",
  59: "Accepted",
  60: "In progress",
  61: "Completed",
  62: "Canceled",
  63: "Booking",
  64: "Call now",
  65: "Message",
  66: "Booking ID",
  67: "New Request",
  68: "Booking Accepted",
  69: "Accepted on",
  70: "Start a job",
  71: "Scheduled on",
  72: "Job Completed",
  73: "Payment will appear here",
  74: "Pricing",
  75: "Quantity",
  76: "Tax amount",
  77: "Total",
  78: "Requested on",
  79: "Payment",
  80: "Make payment",
  81: "Cash payment",
  82: "Confirm Payment",
  83: "Review",
  84: "Leave a Review",
  85: "Chatting online",
  86: "Write your review",
  87: "Tell us something about this service",
  88: "Click on the stars to rate this service",
  89: "Submit Review",
  90: "Add Images",
  91: "From Gallery",
  92: "From Camera",
  93: "Home services",
  94: "Find what you need",
  95: "Search service",
  96: "Notify",
  97: "Duration",
  98: "min",
  99: "This service can take up to",
  100: "Galleries",
  101: "Reviews & Ratings",
  102: "Book This Service",
  103: "Your address",
  104: "Add new",
  105: "Hint",
  106: "Is there anything else",
  107: "Coupon Code",
  108: "Apply",
  109: "Any Time",
  110: "Schedule an Order",
  111: "Requested Service on",
  112: "Select a Date & Time",
  113: "CONFIRM & BOOKING NOW",
  114: "OK",
  115:
      "Your booking has been successfully submitted, you will receive a confirmation soon.",
  116: "Thank you!",
  117: "Add Address",
  118: "My Home",
  119: "Full address",
  120: "Select address",
  121: "Pick here",
  122: "Search",
  123: "Monday",
  124: "Tuesday",
  125: "Wednesday",
  126: "Thursday",
  127: "Friday",
  128: "Saturday",
  129: "Sunday",
  130: "fixed",
  131: "hourly",
  132: "start from",
  133: "Please enter address",
  134: "Please select address",
  135: "Please Enter Email",
  136: "Please Enter Password",
  137: "User not found",
  138: "User don't create",
  139: "Email are wrong",
  140: "Passwords are not equal",
  141: "Phone number must be ",
  142: "symbols",
  143: "Code sent. Please check your phone for the verification code.",
  144: "Time Out",
  145: "Today",
  146: "About Us",
  147: "Known About Us",
  148: "Terms & Conditions",
  149: "Known Terms & Conditions",
  150: "Not found ...",
  151: "Enter Confirm Password",
  152: "Password changed",
  153: "Please Enter name",
  154: "Data saved",
  155: "Provider",
  156: "Chat message",
  157: "New Booking was arrived",
  158: "Now status:",
  159: "Booking status was changed",
  160: "From user:",
  161: "Rate this service",
  162: "Coupon not found",
  163: "Coupon activated",
  164: "Coupon not supported by this provider",
  165: "Coupon not support this category",
  166: "Coupon not support this service",
  167: "Coupon",
  168: "no",
  169: "Coupon has expired",
  170: "Your Favorites",
  171: "View your favorite services",
  172: "Top Services",
  173: "User is disabled. Connect to Administrator for more information.",
  174: "Blog",
  175: "View all",
  176: "Loading ...",
  177: "Service",
  178: "Are you sure you want to exit?",
  179: "No",
  180: "Exit",
  181: "Filter",
  182: "Sort by",
  183: "Ascending (A-Z)",
  184: "Descending (Z-A)",
  185: "Price",
  186: "Reset Filter",
  187: "Apply Filter",
  188: "My Address",
  189: "Address not found",
  190: "Home",
  191: "Office",
  192: "Other",
  193: "Set Location",
  194: "Find services near your",
  195:
      "By allowing location access, you can search for services and providers near your.",
  196: "Use currents location",
  197: "Set from map",
  198: "Add the location",
  199: "Label as",
  200: "Delivery Address",
  201: "Enter Delivery Address",
  202: "Contact name",
  203: "Enter Contact name",
  204: "Contact phone number",
  205: "Enter Contact phone number",
  206: "Save location",
  207: "Latitude",
  208: "Longitude",
  209: "Please enter phone",
  210: "by administrator",
  211: "by provider",
  212: "by customer",
  213: "Enter address",
  214: "Current address",
  215: "Other addresses",
  216: "Location",
  217: "Your address is outside provider work area",
  218: "See details",
  219: "Special Requests",
  220: "Provider Location",
  221: "Addons",
  222: "Nearby you",
  223: "Far",
  224: "Providers",
  225: "Please enter valid code",
  226: "Your phone number verified. You can't edit phone number",
  227: "Forgot password?",
  228: "Reset password",
  229: "Send new password",
  230: "Reset password email sent. Please check your mail.",
  231: "Time creation",
  232: "Booking ID",
  233: "Please enter text",
  234: "Please enter code",
  235: "Subtotal",
  236: "Discount",
  237: "Subcategory",
  238: "Share this app",
  239: "Services nearby",
  240: "Open Provider Page",
  241: "Report ...",
  242: "Block user",
  243: "Block",
  244:
      "They won't be able to message you. You won't be able to message them. They won't be notified that you blocked them. ",
  245: "User",
  246: "Cancel",
  247: "blocked",
  248: "Why are you reporting this user?",
  249:
      "Your report is anonymous, except if you're reporting an intellectual property infringement. ",
  250: "Thanks for letting us know",
  251: "Your feedback is important in helping us keep the community safe. ",
  252: "Unblock",
  253:
      "They be able to message you. You be able to message them. They won't be notified that you unblocked them. ",
  254: "unblocked",
  255: "Your Favorite Providers",
  256: "View your favorite providers",
  257: "Favorite Providers",
  258: "Enable Notify",
  259: "Not available Now",
  260: "Services",
  261: "Provider products",
  262: "Not available Now",
  263: "Total amount",
  264: "Add to cart",
  265: "Please select variant",
  266: "in stock",
  267: "Product added to cart",
  268: "Cart",
  269: "My Cart",
  270: "Proceed to checkout",
  271: "Your cart is empty",
  272: "Item price",
  273: "This service already in the cart",
  274: "This product already in the cart",
  275: "Service added to cart",
  276: "VAT/TAX",
  277: "See more",
  278: "Products",
  279: "Search products",
  280: "Sort by provider",
  281: "Not select",
  282: "Related products",
  283: "Other products",
  284: "Booking At",
  285: "Minimum purchase amount for this provider: ",
  286: "Maximum purchase amount for this provider: ",
  287: "Pay with",
  288: "Provider can't enter to customer app. Please use another credentials.",
  289: "Add promo",
  290: "Promo not found",
  291: "My rewards",
  292: "Enter code",
  293: "Special offer",
  294: "Use now",
  295: "Valid until",
  296: "Your promo code",
  297: "Apply code",
  298: "Coupon not support this product",
  299: "Promo code",
  300: "Remove",
};

Map<int, String> servicesHindi = {
  0: "Oclif",
  1: "सेवा",
  2: "सबमिट करें",
  3: "भाषा",
  4: "पसंदीदा भाषा",
  5: "पसंदीदा भाषा चुनें",
  6: "होम",
  7: "चैट",
  8: "बुकिंग",
  9: "खाता",
  10: "भाषा बदलें",
  11: "अपनी पसंदीदा भाषा सेट करें",
  12: "डार्क मोड सक्षम करें",
  13: "आप पसंदीदा मोड सेट करें",
  14: "गोपनीयता नीति",
  15: "हमारी गोपनीयता नीति को जानें",
  16: "प्रोफाइल देखें",
  17: "लॉग आउट",
  18: "सत्र समाप्त करें",
  19: "सूचनाएं",
  20: "बहुत सारी महत्वपूर्ण जानकारी",
  21: "नाम",
  22: "अपना नाम दर्ज करें",
  23: "ईमेल",
  24: "अपना ईमेल दर्ज करें",
  25: "फोन नंबर",
  26: "अपना फोन नंबर दर्ज करें",
  27: "पता",
  28: "ग्राहकों के लिए पता दर्ज करें",
  29: "विवरण",
  30: "अपने बारे में संक्षिप्त विवरण दर्ज करें",
  31: "बचाओ",
  32: "पासवर्ड बदलें",
  33: "नया पासवर्ड",
  34: "पासवर्ड दर्ज करें",
  35: "नए पासवर्ड की पुष्टि करें",
  36: "पासवर्ड दर्ज करें",
  37: "पासवर्ड बदलें",
  38: "माई प्रोफाइल",
  39: "आपके बारे में सब कुछ",
  40: "समीक्षाएं",
  41: "सभी पढ़ें",
  42: "औसत रेटिंग",
  43: "अभी साइन इन करें",
  44: "पासवर्ड",
  45: "अपना पासवर्ड दर्ज करें",
  46: "जारी रखें",
  47: "रजिस्टर",
  48: "या जारी रखें",
  49: "रजिस्टर",
  50: "एक मिनट से भी कम समय में",
  51: "पासवर्ड की पुष्टि करें",
  52: "सत्यापन",
  53: "हम सत्यापन कोड भेजेंगे।",
  54: "हमने ६ अंकों का सत्यापन कोड भेजा है।",
  55: "कोड दर्ज करें",
  56: "6 अंकों का कोड दर्ज करें",
  57: "अपना संदेश लिखें ...",
  58: "नया",
  59: "स्वीकृत",
  60: "प्रगति में",
  61: "पूर्ण",
  62: "रद्द",
  63: "बुकिंग",
  64: "अभी कॉल करें",
  65: "संदेश",
  66: "बुकिंग आईडी",
  67: "नया अनुरोध",
  68: "बुकिंग स्वीकृत",
  69: "पर स्वीकार किया",
  70: "नौकरी शुरू करें",
  71: "अनुसूचित",
  72: "काम पूरा हुआ",
  73: "भुगतान यहां दिखाई देगा",
  74: "मूल्य निर्धारण",
  75: "मात्रा",
  76: "कर राशि",
  77: "कुल",
  78: "अनुरोध किया गया",
  79: "भुगतान",
  80: "भुगतान करें",
  81: "नकद भुगतान",
  82: "भुगतान की पुष्टि करें",
  83: "समीक्षा",
  84: "एक समीक्षा छोड़ें",
  85: "ऑनलाइन चैटिंग",
  86: "अपनी समीक्षा लिखें",
  87: "हमें इस सेवा के बारे में कुछ बताएं",
  88: "इस सेवा को रेट करने के लिए सितारों पर क्लिक करें",
  89: "समीक्षा सबमिट करें",
  90: "छवियां जोड़ें",
  91: "गैलरी से",
  92: "कैमरा से",
  93: "घरेलू सेवाएं",
  94: "आपको जो चाहिए वो ढूंढें",
  95: "खोज सेवा",
  96: "सूचित करें",
  97: "अवधि",
  98: "मिनट",
  99: "इस सेवा में अधिक समय लग सकता है",
  100: "दीर्घाएँ",
  101: "समीक्षा और रेटिंग",
  102: "यह सेवा बुक करें",
  103: "आपका पता",
  104: "नया जोड़ें",
  105: "संकेत",
  106: "क्या कुछ और है",
  107: "कूपन कोड",
  108: "लागू करें",
  109: "किसी भी समय",
  110: "एक आदेश निर्धारित करें",
  111: "अनुरोधित सेवा चालू",
  112: "एक तिथि और समय चुनें",
  113: "अभी पुष्टि करें और बुकिंग करें",
  114: "ठीक है",
  115:
      "आपकी बुकिंग सफलतापूर्वक सबमिट कर दी गई है, आपको जल्द ही एक पुष्टिकरण प्राप्त होगा।",
  116: "धन्यवाद!",
  117: "पता जोड़ें",
  118: "माई होम",
  119: "पूरा पता",
  120: "पता चुनें",
  121: "यहाँ उठाओ",
  122: "खोज",
  123: "सोमवार",
  124: "मंगलवार",
  125: "बुधवार",
  126: "गुरुवार",
  127: "शुक्रवार",
  128: "शनिवार",
  129: "रविवार",
  130: "निश्चित",
  131: "प्रति घंटा",
  132: "से शुरू करें",
  133: "कृपया पता दर्ज करें",
  134: "कृपया पता चुनें",
  135: "कृपया ईमेल दर्ज करें",
  136: "कृपया पासवर्ड दर्ज करें",
  137: "उपयोगकर्ता नहीं मिला",
  138: "उपयोगकर्ता नहीं बनाते",
  139: "ईमेल गलत हैं",
  140: "पासवर्ड समान नहीं हैं",
  141: "फ़ोन नंबर होना चाहिए",
  142: "प्रतीक",
  143: "कोड भेजा गया। कृपया सत्यापन कोड के लिए अपने फोन की जांच करें।",
  144: "टाइम आउट",
  145: "आज",
  146: "हमारे बारे में",
  147: "हमारे बारे में जाना जाता है",
  148: "नियम और शर्तें",
  149: "ज्ञात नियम और शर्तें",
  150: "नहीं मिला ...",
  151: "पासवर्ड की पुष्टि दर्ज करें",
  152: "पासवर्ड बदल गया",
  153: "कृपया नाम दर्ज करें",
  154: "डेटा सहेजा गया",
  155: "प्रदाता",
  156: "चैट संदेश",
  157: "नई बुकिंग आ गई",
  158: "अब स्थिति:",
  159: "बुकिंग की स्थिति बदली गई",
  160: "उपयोगकर्ता से:",
  161: "इस सेवा को रेट करें",
  162: "कूपन नहीं मिला",
  163: "कूपन सक्रिय",
  164: "कूपन इस प्रदाता द्वारा समर्थित नहीं है",
  165: "कूपन इस श्रेणी का समर्थन नहीं करता",
  166: "कूपन इस सेवा का समर्थन नहीं करता",
  167: "कूपन",
  168: "नहीं",
  169: "कूपन समाप्त हो गया है",
  170: "आपका पसंदीदा",
  171: "अपनी पसंदीदा सेवाएं देखें",
  172: "सर्वोच्च सेवाएं",
  173: "उपयोगकर्ता अक्षम है। अधिक जानकारी के लिए व्यवस्थापक से कनेक्ट करें।",
  174: "ब्लॉग",
  175: "सभी देखें",
  176: "लोड हो रहा है ...",
  177: "सेवा",
  178: "क्या आप वाकई बाहर निकलना चाहते हैं?",
  179: "नहीं",
  180: "बाहर निकलें",
  181: "फ़िल्टर",
  182: "क्रमबद्ध करें",
  183: "आरोही (ए-जेड)",
  184: "अवरोही (जेड-ए)",
  185: "कीमत",
  186: "फ़िल्टर रीसेट करें",
  187: "फ़िल्टर लागू करें",
  188: "मेरा पता",
  189: "पता नहीं मिला",
  190: "होम",
  191: "कार्यालय",
  192: "अन्य",
  193: "स्थान निर्धारित करें",
  194: "अपने आस-पास की सेवाओं का पता लगाएं",
  195:
      "लोकेशन एक्सेस की अनुमति देकर, आप अपने आस-पास की सेवाओं और प्रदाताओं की खोज कर सकते हैं।",
  196: "करंट लोकेशन का उपयोग करें",
  197: "मानचित्र से सेट करें",
  198: "स्थान जोड़ें",
  199: "लेबल के रूप में",
  200: "वितरण पता",
  201: "डिलीवरी का पता दर्ज करें",
  202: "संपर्क नाम",
  203: "संपर्क नाम दर्ज करें",
  204: "फोन नंबर से संपर्क करें",
  205: "संपर्क फोन नंबर दर्ज करें",
  206: "स्थान सहेजें",
  207: "अक्षांश",
  208: "देशांतर",
  209: "कृपया फोन दर्ज करें",
  210: "व्यवस्थापक द्वारा",
  211: "प्रदाता द्वारा",
  212: "ग्राहक द्वारा",
  213: "पता दर्ज करें",
  214: "वर्तमान पता",
  215: "अन्य पते",
  216: "स्थान",
  217: "आपका पता प्रदाता के कार्य क्षेत्र के बाहर है",
  218: "विवरण देखें",
  219: "विशेष अनुरोध",
  220: "प्रदाता स्थान",
  221: "एडॉन्स",
  222: "आपके आस-पास",
  223: "दूर",
  224: "प्रदाता",
  225: "कृपया वैध कोड दर्ज करें",
  226: "आपका फ़ोन नंबर सत्यापित है। आप फ़ोन नंबर संपादित नहीं कर सकते",
  227: "पासवर्ड भूल गए?",
  228: "पासवर्ड रीसेट करें",
  229: "नया पासवर्ड भेजें",
  230: "रीसेट पासवर्ड ईमेल भेजा गया। कृपया अपना मेल जांचें।",
  231: "समय निर्माण",
  232: "बुकिंग आईडी",
  233: "कृपया टेक्स्ट दर्ज करें",
  234: "कृपया कोड दर्ज करें",
  235: "सबटोटल",
  236: "छूट",
  237: "उपश्रेणी",
  238: "इस ऐप को साझा करें",
  239: "आस-पास की सेवाएं",
  240: "ओपन प्रोवाइडर पेज",
  241: "रिपोर्ट ...",
  242: "ब्लॉक यूजर",
  243: "ब्लॉक",
  244:
      "वे आपको मैसेज नहीं कर पाएंगे। आप उन्हें मैसेज नहीं कर पाएंगे। उन्हें सूचित नहीं किया जाएगा कि आपने उन्हें ब्लॉक कर दिया है।",
  245: "उपयोगकर्ता",
  246: "रद्द करें",
  247: "अवरुद्ध",
  248: "आप इस उपयोगकर्ता की रिपोर्ट क्यों कर रहे हैं?",
  249:
      "आपकी रिपोर्ट गुमनाम है, सिवाय इसके कि आप किसी बौद्धिक संपदा उल्लंघन की रिपोर्ट कर रहे हैं।",
  250: "हमें बताने के लिए धन्यवाद",
  251:
      "समुदाय को सुरक्षित रखने में हमारी मदद करने के लिए आपकी प्रतिक्रिया महत्वपूर्ण है।",
  252: "अनब्लॉक करें",
  253:
      "वे आपको संदेश भेज सकेंगे। आप उन्हें संदेश भेज सकेंगे। उन्हें सूचित नहीं किया जाएगा कि आपने उन्हें अनब्लॉक कर दिया है।",
  254: "अनब्लॉक",
  255: "आपके पसंदीदा प्रदाता",
  256: "अपने पसंदीदा प्रदाताओं को देखें",
  257: "पसंदीदा प्रदाता",
  258: "सूचना सक्षम करें",
  259: "अभी उपलब्ध नहीं है",
  260: "सेवाएं",
  261: "प्रदाता उत्पाद",
  262: "अभी उपलब्ध नहीं है",
  263: "कुल राशि",
  264: "कार्ट में जोड़ें",
  265: "कृपया प्रकार चुनें",
  266: "स्टॉक में",
  267: "कार्ट में जोड़ा गया उत्पाद",
  268: "गाड़ी",
  269: "माई कार्ट",
  270: "चेकआउट के लिए आगे बढ़ें",
  271: "आपकी गाड़ी खाली है",
  272: "आइटम की कीमत",
  273: "यह सेवा पहले से ही कार्ट में है",
  274: "यह उत्पाद पहले से ही कार्ट में है",
  275: "सेवा कार्ट में जोड़ी गई",
  276: "वैट/टैक्स",
  277: "और देखें",
  278: "उत्पाद",
  279: "उत्पाद खोजें",
  280: "प्रदाता द्वारा क्रमबद्ध करें",
  281: "नहीं चुनें",
  282: "संबंधित उत्पाद",
  283: "अन्य उत्पाद",
  284: "बुकिंग एट",
  285: "इस प्रदाता के लिए न्यूनतम खरीद राशि:",
  286: "इस प्रदाता के लिए अधिकतम खरीद राशि:",
  287: "के साथ भुगतान करें",
  288:
      "प्रदाता ग्राहक ऐप में प्रवेश नहीं कर सकता। कृपया अन्य क्रेडेंशियल का उपयोग करें।",
  289: "प्रोमो जोड़ें",
  290: "प्रोमो नहीं मिला",
  291: "मेरे पुरस्कार",
  292: "कोड दर्ज करें",
  293: "विशेष पेशकश",
  294: "अभी उपयोग करें",
  295: "तक मान्य",
  296: "आपका प्रोमो कोड",
  297: "कोड लागू करें",
  298: "कूपन इस उत्पाद का समर्थन नहीं करता",
  299: "प्रोमो कोड",
  300: "निकालें",
};
