Map<int, String> providerEng = {
  0: "Oclif",
  1: "PROVIDER",
  2: "SUBMIT",
  3: "Language",
  4: "Preferred Language",
  5: "Select Preferred Language",
  6: "Sign in now",
  7: "Email",
  8: "Enter your Email",
  9: "Password",
  10: "Enter your Password",
  11: "CONTINUE",
  12: "REGISTER",
  13: "or continue with",
  14: "Register",
  15: "in less than a minute",
  16: "Name",
  17: "Enter Name",
  18: "Confirm Password",
  19: "Verification",
  20: "Phone number",
  21: "Enter your Phone number",
  22: "We'll sent verification code.",
  23: "We've sent 6 digit verification code.",
  24: "Enter code",
  25: "Enter 6 digits code",
  26: "Chat",
  27: "Booking",
  28: "Account",
  29: "Write your message ...",
  30: "Any Time",
  31: "Upcoming",
  32: "Completed",
  33: "Canceled",
  34: "New",
  35: "Canceled",
  36: "Completed",
  37: "Accepted",
  38: "Call now",
  39: "Message",
  40: "Accept",
  41: "Start a job",
  42: "Job complete",
  43: "Waiting for Confirmation from Customer",
  44: "Booking ID",
  45: "Request Received",
  46: "Requested on",
  47: "Booking Confirmed",
  48: "Confirmed on",
  49: "Start a job",
  50: "Scheduled on",
  51: "Job Completed",
  52: "Payment will appear here",
  53: "Pricing",
  54: "Quantity",
  55: "Tax amount",
  56: "Total",
  57: "View profile",
  58: "reviews",
  59: "Read all",
  60: "Change Language",
  61: "Set your Preferred language",
  62: "Enter your Email",
  63: "Address",
  64: "Enter address for customers",
  65: "Description",
  66: "Enter Short description about you",
  67: "SAVE",
  68: "Change password",
  69: "New password",
  70: "Enter Password",
  71: "Confirm New password",
  72: "CHANGE PASSWORD",
  73: "My Profile",
  74: "Everything about you",
  75: "Average Ratings",
  76: "Enable Dark Mode",
  77: "Set you favorite mode",
  78: "Wallet",
  79: "Know your earnings",
  80: "My Portfolio",
  81: "Upload your best works",
  82: "Privacy Policy",
  83: "Known our Privacy Policy",
  84: "From Gallery",
  85: "From Camera",
  86: "Delete",
  87: "Set invisible",
  88: "Available Balance",
  89: "Notifications",
  90: "Lots of important information",
  91: "Log Out",
  92: "End the session",
  93: "Please Enter Email",
  94: "Please Enter Password",
  95: "User not found",
  96: "User is disabled. Connect to Administrator for more information.",
  97: "Passwords are not equal",
  98: "Email are wrong",
  99: "User don't create",
  100:
      "You account created. After moderation your account will be activated. We will inform you.",
  101: "Chatting online",
  102: "Search",
  103: "Chat message",
  104: "Notifications",
  105: "Lots of important information",
  106: "Today",
  107: "Not found ...",
  108: "About Us",
  109: "Known About Us",
  110: "Terms & Conditions",
  111: "Known Terms & Conditions",
  112: "Enter your name",
  113: "Enter Confirm Password",
  114: "Password changed",
  115: "Please Enter name",
  116: "Data saved",
  117: "Booking status was changed",
  118: "Now status:",
  119: "by customer",
  120: "by provider",
  121: "by administrator",
  122: "Money transfer",
  123: "My page",
  124: "Edit Provider information",
  125: "Monday",
  126: "Tuesday",
  127: "Wednesday",
  128: "Thursday",
  129: "Friday",
  130: "Saturday",
  131: "Sunday",
  132: "Galleries",
  133: "Edit",
  134: "Save",
  135: "Enter your Phone",
  136: "Enter your Web Page address",
  137: "Enter your Instagram address",
  138: "Enter your Telegram address",
  139: "Change",
  140: "Add from galley",
  141: "Add from camera",
  142: "My Services",
  143: "Edit Service information",
  144: "Search service",
  145: "Do you want to delete this item? You will can't recover this item.",
  146: "No",
  147: "This is Demo Mode. You can't modify this section",
  148: "Edit Service",
  149: "Visible",
  150: "Select Language",
  151: "Tax",
  152: "Description Title",
  153: "Price",
  154: "Discount price",
  155: "Price Unit",
  156: "Hourly",
  157: "Fixed",
  158: "Select image",
  159: "Addons",
  160: "Add addon",
  161: "Gallery",
  162: "Image deleted",
  163: "Add image to gallery",
  164: "Service duration",
  165: "min",
  166: "Only selected",
  167: "Categories",
  168: "Providers",
  169: "Save current service",
  170: "Please enter price",
  171: "Please select provider",
  172: "Please enter category",
  173: "Save addon",
  174: "Close",
  175: "Select",
  176:
      "Addon will be deleted from all services in current Provider. Do you want to delete this item? You will can't recover this item. ",
  177: "Data deleted",
  178: "Create new service",
  179: "My Work Area",
  180: "Edit your work area",
  181: "Delete current",
  182: "Forgot password?",
  183: "Reset password",
  184: "Send new password",
  185: "Reset password email sent. Please check your mail.",
  186: "Time creation",
  187: "Please Enter phone",
  188:
      "Please leave information for us to make it easier for us to work with you.",
  189: "Provider Name",
  190: "Home service",
  191: "Login",
  192: "Phone",
  193: "Set my Work Area",
  194: "Set Profile Image",
  195: "Please Enter Provider Name",
  196: "Please Enter description",
  197: "Please Enter address",
  198: "Please upload Profile Image",
  199: "Please select work area",
  200: "Please select Category where you will work",
  201: "Please Enter Login",
  202: "Payment method",
  203: "Subtotal",
  204: "Discount",
  205: "User must be Provider",
  206: "Provider Information not found",
  207: "Are you sure you want to exit?",
  208: "Exit",
  209: "On map",
  210: "Customer location",
  211: "Customer address",
  212: "Enable Notify",
  213: "Provider Available/Unavailable",
  214: "Temporary disable your account",
  215: "VAT/TAX",
  216: "Total amount",
  217: "Booking At",
  218: "Customer name",
  219: "To Admin",
  220: "To Provider",
  221: "TAX/VAT",
  222: "Payouts",
  223: "Balance",
  224: "Orders",
  225: "My Products",
  226: "Edit Products information",
  227: "Search in this list",
  228: "Create new product",
  229: "Not available Now",
  230: "Add image URL",
  231: "Description:",
  232: "You can use HTML tags (<p>, <br>, <h1> and other)",
  233: "Variants",
  234: "Add new group",
  235: "Add new variant",
  236: "Save current product",
  237: "Add New Product",
  238: "Unit",
  239: "In Stock",
  240: "pcs",
  241: "Please select variant",
  242: "Save group",
  243: "Add group",
  244: "Group name",
  245: "Preview",
  246: "URL",
  247: "Add image",
  248: "Variant name",
  249: "Add image from gallery (optional)",
  250: "or",
  251: "Add image URL (optional)",
  252: "influence on price +/-",
  253: "Save variant",
  254: "Add variant",
  255: "Please select stock",
  256: "influence must start with + or -",
  257: "Close",
  258: "Add image from camera",
  259: "Add image from camera (optional)",
  260: "Please upload image",
  261: "Cancel",
  262:
      "You have exceeded the limit on the number of services. Contact support for more information.",
  263: "Category tree",
  264: "Price can't be 0",
  265:
      "You have exceeded the limit on the number of addons on one service. Contact support for more information.",
  266:
      "You have exceeded the limit on the number of products. Contact support for more information.",
  267: "Minimum order amount",
  268: "Maximum order amount",
  269: "Settings",
  270: "Set minimum amd maximum order amounts",
  271: "Please enter minimum order amount",
  272: "Please enter maximum order amount",
  273: "Allow booking only if customer located in provider work area",
  274: "Subscription Status",
  275: "Expire date",
  276: "Subscribed",
  277: "Not Subscribed",
  278: "Subscribe now",
  279: "Extend your subscription",
  280: "",
  281: "Start Free Trial Now",
  282: "Start",
  283: "Pay with",
  284: "You subscriptions expired",
  285: "Expired",
  286: "Confirm Subscription. Do you want to subscribe for Two month for",
  287: "Free Trial",
};

Map<int, String> providerHindi = {
  0: "Oclif",
  1: "प्रदाता",
  2: "सबमिट करें",
  3: "भाषा",
  4: "पसंदीदा भाषा",
  5: "पसंदीदा भाषा चुनें",
  6: "अभी साइन इन करें",
  7: "ईमेल",
  8: "अपना ईमेल दर्ज करें",
  9: "पासवर्ड",
  10: "अपना पासवर्ड दर्ज करें",
  11: "जारी रखें",
  12: "रजिस्टर",
  13: "या जारी रखें",
  14: "रजिस्टर",
  15: "एक मिनट से भी कम समय में",
  16: "नाम",
  17: "नाम दर्ज करें",
  18: "पासवर्ड की पुष्टि करें",
  19: "सत्यापन",
  20: "फोन नंबर",
  21: "अपना फोन नंबर दर्ज करें",
  22: "हम सत्यापन कोड भेजेंगे।",
  23: "हमने 6 अंकों का सत्यापन कोड भेजा है।",
  24: "कोड दर्ज करें",
  25: "6 अंकों का कोड दर्ज करें",
  26: "चैट",
  27: "बुकिंग",
  28: "खाता",
  29: "अपना संदेश लिखें ...",
  30: "बुकिंग",
  31: "आगामी",
  32: "पूर्ण",
  33: "रद्द",
  34: "नया",
  35: "रद्द किया गया",
  36: "पूर्ण",
  37: "स्वीकृत",
  38: "अभी कॉल करें",
  39: "संदेश",
  40: "स्वीकार करें",
  41: "नौकरी शुरू करें",
  42: "काम पूरा",
  43: "ग्राहक से पुष्टि की प्रतीक्षा में",
  44: "बुकिंग आईडी",
  45: "अनुरोध प्राप्त हुआ",
  46: "अनुरोध किया गया",
  47: "बुकिंग कन्फर्म",
  48: "पुष्टि की गई",
  49: "नौकरी शुरू करें",
  50: "अनुसूचित",
  51: "काम पूरा हुआ",
  52: "भुगतान यहां दिखाई देगा",
  53: "मूल्य निर्धारण",
  54: "मात्रा",
  55: "कर राशि",
  56: "कुल",
  57: "प्रोफाइल देखें",
  58: "समीक्षाएं",
  59: "सभी पढ़ें",
  60: "भाषा बदलें",
  61: "अपनी पसंदीदा भाषा सेट करें",
  62: "अपना ईमेल दर्ज करें",
  63: "पता",
  64: "ग्राहकों के लिए पता दर्ज करें",
  65: "विवरण",
  66: "अपने बारे में संक्षिप्त विवरण दर्ज करें",
  67: "बचाओ",
  68: "पासवर्ड बदलें",
  69: "नया पासवर्ड",
  70: "पासवर्ड दर्ज करें",
  71: "नए पासवर्ड की पुष्टि करें",
  72: "पासवर्ड बदलें",
  73: "माई प्रोफाइल",
  74: "आपके बारे में सब कुछ",
  75: "औसत रेटिंग",
  76: "डार्क मोड सक्षम करें",
  77: "आप पसंदीदा मोड सेट करें",
  78: "वॉलेट",
  79: "अपनी कमाई जानो",
  80: "मेरा पोर्टफोलियो",
  81: "अपना सर्वश्रेष्ठ कार्य अपलोड करें",
  82: "गोपनीयता नीति",
  83: "हमारी गोपनीयता नीति को जानें",
  84: "गैलरी से",
  85: "कैमरा से",
  86: "हटाएं",
  87: "अदृश्य सेट करें",
  88: "उपलब्ध शेष",
  89: "सूचनाएं",
  90: "बहुत सारी महत्वपूर्ण जानकारी",
  91: "लॉग आउट",
  92: "सत्र समाप्त करें",
  93: "कृपया ईमेल दर्ज करें",
  94: "कृपया पासवर्ड दर्ज करें",
  95: "उपयोगकर्ता नहीं मिला",
  96: "उपयोगकर्ता अक्षम है। अधिक जानकारी के लिए व्यवस्थापक से कनेक्ट करें।",
  97: "पासवर्ड समान नहीं हैं",
  98: "ईमेल गलत हैं",
  99: "उपयोगकर्ता नहीं बनाते",
  100:
      "आपने खाता बना लिया। मॉडरेशन के बाद आपका खाता सक्रिय हो जाएगा। हम आपको सूचित करेंगे।",
  101: "ऑनलाइन चैटिंग",
  102: "खोज",
  103: "चैट संदेश",
  104: "सूचनाएं",
  105: "बहुत सारी महत्वपूर्ण जानकारी",
  106: "आज",
  107: "नहीं मिला ...",
  108: "हमारे बारे में",
  109: "हमारे बारे में जाना जाता है",
  110: "नियम और शर्तें",
  111: "ज्ञात नियम और शर्तें",
  112: "अपना नाम दर्ज करें",
  113: "पासवर्ड की पुष्टि करें दर्ज करें",
  114: "पासवर्ड बदल गया",
  115: "कृपया नाम दर्ज करें",
  116: "डेटा सहेजा गया",
  117: "बुकिंग की स्थिति बदली गई",
  118: "अब स्थिति:",
  119: "ग्राहक द्वारा",
  120: "प्रदाता द्वारा",
  121: "व्यवस्थापक द्वारा",
  122: "मनी ट्रांसफर",
  123: "मेरा पेज",
  124: "प्रदाता जानकारी संपादित करें",
  125: "सोमवार",
  126: "मंगलवार",
  127: "बुधवार",
  128: "गुरुवार",
  129: "शुक्रवार",
  130: "शनिवार",
  131: "रविवार",
  132: "दीर्घाएँ",
  133: "संपादित करें",
  134: "सहेजें",
  135: "अपना फोन दर्ज करें",
  136: "अपना वेब पेज पता दर्ज करें",
  137: "अपना इंस्टाग्राम पता दर्ज करें",
  138: "अपना टेलीग्राम पता दर्ज करें",
  139: "बदलें",
  140: "गैली से जोड़ें",
  141: "कैमरा से जोड़ें",
  142: "मेरी सेवाएं",
  143: "सेवा जानकारी संपादित करें",
  144: "खोज सेवा",
  145:
      "क्या आप इस आइटम को हटाना चाहते हैं? आप इस आइटम को पुनर्प्राप्त नहीं कर सकते।",
  146: "नहीं",
  147: "यह डेमो मोड है। आप इस अनुभाग को संशोधित नहीं कर सकते",
  148: "सेवा संपादित करें",
  149: "दृश्यमान",
  150: "भाषा चुनें",
  151: "टैक्स",
  152: "विवरण शीर्षक",
  153: "कीमत",
  154: "डिस्काउंट प्राइस",
  155: "मूल्य इकाई",
  156: "प्रति घंटा",
  157: "फिक्स्ड",
  158: "छवि का चयन करें",
  159: "एडॉन्स",
  160: "एडऑन जोड़ें",
  161: "गैलरी",
  162: "छवि हटाई गई",
  163: "गैलरी में छवि जोड़ें",
  164: "सेवा अवधि",
  165: "मिनट",
  166: "केवल चयनित",
  167: "श्रेणियाँ",
  168: "प्रदाता",
  169: "वर्तमान सेवा सहेजें",
  170: "कृपया कीमत दर्ज करें",
  171: "कृपया प्रदाता का चयन करें",
  172: "कृपया श्रेणी दर्ज करें",
  173: "सहेजें ऐडऑन",
  174: "बंद करें",
  175: "चुनें",
  176:
      "Addon वर्तमान प्रदाता में सभी सेवाओं से हटा दिया जाएगा। क्या आप इस आइटम को हटाना चाहते हैं? आप इस आइटम को पुनर्प्राप्त नहीं कर पाएंगे।",
  177: "डेटा हटा दिया गया",
  178: "नई सेवा बनाएं",
  179: "मेरा कार्य क्षेत्र",
  180: "अपना कार्य क्षेत्र संपादित करें",
  181: "वर्तमान हटाएं",
  182: "पासवर्ड भूल गए?",
  183: "पासवर्ड रीसेट करें",
  184: "नया पासवर्ड भेजें",
  185: "रीसेट पासवर्ड ईमेल भेजा गया। कृपया अपना मेल जांचें।",
  186: "समय निर्माण",
  187: "कृपया फोन दर्ज करें",
  188:
      "कृपया हमारे लिए जानकारी छोड़ दें ताकि हमारे लिए आपके साथ काम करना आसान हो सके।",
  189: "प्रदाता का नाम",
  190: "होम सर्विस",
  191: "लॉगिन",
  192: "फोन",
  193: "मेरा कार्य क्षेत्र निर्धारित करें",
  194: "प्रदाता लोगो सेट करें",
  195: "कृपया प्रदाता का नाम दर्ज करें",
  196: "कृपया विवरण दर्ज करें",
  197: "कृपया पता दर्ज करें",
  198: "कृपया प्रदाता लोगो अपलोड करें",
  199: "कृपया कार्य क्षेत्र का चयन करें",
  200: "कृपया उस श्रेणी का चयन करें जहाँ आप काम करेंगे",
  201: "कृपया लॉगिन दर्ज करें",
  202: "भुगतान विधि",
  203: "सबटोटल",
  204: "छूट",
  205: "उपयोगकर्ता प्रदाता होना चाहिए",
  206: "प्रदाता की जानकारी नहीं मिली",
  207: "क्या आप वाकई बाहर निकलना चाहते हैं?",
  208: "बाहर निकलें",
  209: "मानचित्र पर",
  210: "ग्राहक स्थान",
  211: "ग्राहक का पता",
  212: "सूचना सक्षम करें",
  213: "प्रदाता उपलब्ध/अनुपलब्ध",
  214: "अपने खाते को अस्थायी रूप से अक्षम करें",
  215: "वैट/टैक्स",
  216: "कुल राशि",
  217: "बुकिंग एट",
  218: "ग्राहक का नाम",
  219: "टू एडमिन",
  220: "प्रदाता के लिए",
  221: "कर/वैट",
  222: "पेआउट",
  223: "बैलेंस",
  224: "आदेश",
  225: "मेरे उत्पाद",
  226: "उत्पाद जानकारी संपादित करें",
  227: "इस सूची में खोजें",
  228: "नया उत्पाद बनाएं",
  229: "अभी उपलब्ध नहीं है",
  230: "छवि URL जोड़ें",
  231: "विवरण:",
  232: "आप HTML टैग्स (<p>, <br>, <h1> और अन्य) का उपयोग कर सकते हैं",
  233: "वेरिएंट",
  234: "नया समूह जोड़ें",
  235: "नया संस्करण जोड़ें",
  236: "वर्तमान उत्पाद सहेजें",
  237: "नया उत्पाद जोड़ें",
  238: "यूनिट",
  239: "स्टॉक में",
  240: "पीसी",
  241: "कृपया प्रकार चुनें",
  242: "समूह सहेजें",
  243: "समूह जोड़ें",
  244: "समूह का नाम",
  245: "पूर्वावलोकन",
  246: "यूआरएल",
  247: "छवि जोड़ें",
  248: "संस्करण नाम",
  249: "गैलरी से छवि जोड़ें (वैकल्पिक)",
  250: "या",
  251: "छवि URL जोड़ें (वैकल्पिक)",
  252: "कीमत +/- पर प्रभाव",
  253: "वैरिएंट सहेजें",
  254: "वैरिएंट जोड़ें",
  255: "कृपया स्टॉक चुनें",
  256: "प्रभाव + या - से शुरू होना चाहिए",
  257: "बंद करें",
  258: "कैमरे से छवि जोड़ें",
  259: "कैमरे से छवि जोड़ें (वैकल्पिक)",
  260: "कृपया छवि अपलोड करें",
  261: "रद्द करें",
  262:
      "आपने सेवाओं की संख्या की सीमा पार कर ली है। अधिक जानकारी के लिए समर्थन से संपर्क करें।",
  263: "श्रेणी वृक्ष",
  264: "कीमत 0 नहीं हो सकती",
  265:
      "आप एक सेवा पर ऐडऑन की संख्या की सीमा पार कर चुके हैं। अधिक जानकारी के लिए समर्थन से संपर्क करें।",
  266:
      "आप उत्पादों की संख्या की सीमा पार कर चुके हैं। अधिक जानकारी के लिए समर्थन से संपर्क करें।",
  267: "न्यूनतम आदेश राशि",
  268: "अधिकतम आदेश राशि",
  269: "सेटिंग्स",
  270: "न्यूनतम और अधिकतम आदेश मात्रा निर्धारित करें",
  271: "कृपया न्यूनतम आदेश राशि दर्ज करें",
  272: "कृपया अधिकतम आदेश राशि दर्ज करें",
  273: "बुकिंग की अनुमति तभी दें जब ग्राहक प्रदाता कार्य क्षेत्र में स्थित हो",
  274: "सदस्यता की स्थिति",
  275: "समाप्ति तिथि",
  276: "सदस्यता ली",
  277: "सदस्यता नहीं ली",
  278: "अभी सदस्यता लें",
  279: "अपनी सदस्यता बढ़ाएँ",
  280: "",
  281: "अभी नि:शुल्क परीक्षण शुरू करें",
  282: "प्रारंभ",
  283: "के साथ भुगतान करें",
  284: "आपकी सदस्यता समाप्त हो गई",
  285: "समाप्त हो गया",
  286: "सदस्यता की पुष्टि करें। क्या आप दो महीने के लिए सदस्यता लेना चाहते हैं",
  287: "नि:शुल्क परीक्षण",
};
