Map<int, String> siteLangEng = {
  0: "Oclif",
  1: "View all",
  2: "Providers",
  3: "Phone",
  4: "WWW",
  5: "Instagram",
  6: "Provider",
  7: "Telegram",
  8: "Monday",
  9: "Tuesday",
  10: "Wednesday",
  11: "Thursday",
  12: "Friday",
  13: "Saturday",
  14: "Sunday",
  15: "Galleries",
  16: "Services",
  17: "Service",
  18: "Top Services",
  19: "Blog",
  20: "Category",
  21: "fixed",
  22: "hourly",
  23: "Addons",
  24: "Duration",
  25: "This service can take up to",
  26: "min",
  27: "Privacy Policy",
  28: "About Us",
  29: "Terms & Conditions",
  30: "Search service",
  31: "Search",
  32: "Welcome, Please Login to continue",
  33: "Email",
  34: "Password",
  35: "Remember me",
  36: "Sign In",
  37: "Username or password is incorrect",
  38: "Permission denied",
  39: "Forgot password?",
  40: "Sign Out",
  41: "or continue with",
  42: "Reset password",
  43: "Email",
  44: "Send new password",
  45: "Reset password email sent, Please check your mail,",
  46: "Back to Login",
  47: "Go back",
  48: "Don't have account, Register",
  49: "Register",
  50: "in less than a minute",
  51: "Name",
  52: "Confirm Password",
  53: "User don't create",
  54: "Please Enter Email",
  55: "Please enter password",
  56: "Passwords are not equal",
  57: "Email are wrong",
  58: "Select Address",
  59: "Verification",
  60: "Phone number",
  61: "We'll sent verification code,",
  62: "CONTINUE",
  63: "Enter your phone number",
  64: "Enter code",
  65: "We've sent 6 digit verification code,",
  66: "Current address",
  67: "Other addresses",
  68: "Address not found",
  69: "Add address",
  70: "Find services near your",
  71: "By allowing location access, you can search for services and providers near your,",
  72: "Use currents location",
  73: "Set from map",
  74: "Latitude",
  75: "Longitude",
  76: "Pick here",
  77: "Please enter address",
  78: "Add the location",
  79: "Label as",
  80: "Home",
  81: "Delivery Address",
  82: "Office",
  83: "Other",
  84: "Contact name",
  85: "Contact phone number",
  86: "Save location",
  87: "Please Enter name",
  88: "Please enter phone",
  89: "Book this service",
  90: "Your address",
  91: "Add new",
  92: "Your address is outside provider work area",
  93: "See details",
  94: "Special Requests",
  95: "Any Time",
  96: "Schedule an Order",
  97: "Select a Date & Time",
  98: "Requested Service on",
  99: "CLOSE",
  100: "Please select address",
  101: "Coupon Code",
  102: "Coupon not found",
  103: "Coupon has expired",
  104: "Coupon not supported by this provider",
  105: "Coupon not support this category",
  106: "Coupon not support this service",
  107: "Coupon activated",
  108: "Quantity",
  109: "Pricing",
  110: "Coupon",
  111: "no",
  112: "Tax amount",
  113: "Total",
  114: "Requested Service on",
  115: "Cash payment",
  116: "CONFIRM & BOOKING NOW",
  117: "From user:",
  118: "New Booking was arrived",
  119: "Thank you!",
  120:
      "Your booking has been successfully submitted, you will receive a confirmation soon,",
  121: "Ok",
  122: "Please enter valid code",
  123: "Account",
  124: "Booking",
  125: "Profile",
  126: "Favorites",
  127: "Notifications",
  128: "My Address",
  129: "Notifications not found",
  130: "SAVE",
  131: "Data saved",
  132: "Change password",
  133: "New password",
  134: "Confirm New password",
  135: "CHANGE PASSWORD",
  136: "Enter Password",
  137: "Enter Confirm Password",
  138: "Passwords are not equal",
  139: "Password changed",
  140: "Favorites not found",
  141: "Full address",
  142: "Please tap on map for select location",
  143: "Not found ,,,",
  144: "Any Time",
  145: "Code sent, Please check your phone for the verification code,",
  146: "Your phone number verified, You can't edit phone number",
  147: "Requested on",
  148: "by administrator",
  149: "by provider",
  150: "by customer",
  151: "Now status:",
  152: "Booking status was changed",
  153: "Rate this provider",
  154: "Id",
  155: "Back to bookings list",
  156: "Time creation",
  157: "Booking ID",
  158: "Rate this service",
  159: "Click on the stars to rate this service",
  160: "Tell us something about this service",
  161: "Add image",
  162: "",
  163: "Submit Review",
  164: "You can add images",
  165: "Please enter text",
  166: "Search on ",
  167: " or ",
  168: "Filter",
  169: "Sort by",
  170: "Ascending (A-Z)",
  171: "Descending (Z-A)",
  172: "Nearby you",
  173: "Far",
  174: "Price",
  175: "Reset Filter",
  176: "Apply Filter",
  177: "Payment cancel!",
  178: "Your booking has been cancelled, you can making booking again,",
  179: "Login",
  180: "Current",
  181: "Subtotal",
  182: "Discount",
  183: "Subcategory",
  184: "Change avatar",
  185: "Favorite Providers",
  186: "Not available Now",
  187: "Related products",
  188: "See more",
  189: "Sort by provider",
  190: "Not select",
  191: "Search service, provider or product",
  193: "Products",
  194: "Add to cart",
  195: "in stock",
  196: "Total amount",
  197: "Please select variant",
  198: "Product added to cart",
  199: "This product already in the cart",
  200: "My Cart",
  201: "Proceed to checkout",
  202: "Your cart in empty",
  203: "Addons:",
  204: "Quantity",
  205: "Item price",
  206: "Other products",
  207: "Is there anything else",
  208: "VAT/TAX",
  209: "Search products",
  210: "Provider products",
  211: "Reviews & Ratings",
  212: "Maximum purchase amount for this provider: ",
  213: "Minimum purchase amount for this provider: ",
  214: "Promo code",
  215: "Remove",
  216: "Add promo",
  217: "Promo not found",
  218: "My rewards",
  219: "Enter code",
  220: "Special offer",
  221: "Use now",
  222: "Valid until",
  223: "Coupon not support this product",
  224: "Apply code",
  225: "Your promo code",
};

Map<int, String> siteLangHindi = {
  0: "Oclif",
  1: "सभी देखें",
  2: "प्रदाता",
  3: "फोन",
  4: "डब्ल्यूडब्ल्यूडब्ल्यू",
  5: "इंस्टाग्राम",
  6: "प्रदाता",
  7: "टेलीग्राम",
  8: "सोमवार",
  9: "मंगलवार",
  10: "बुधवार",
  11: "गुरुवार",
  12: "शुक्रवार",
  13: "शनिवार",
  14: "रविवार",
  15: "दीर्घाएँ",
  16: "सेवाएं",
  17: "सेवा",
  18: "शीर्ष सेवाएं",
  19: "ब्लॉग",
  20: "श्रेणी",
  21: "निश्चित",
  22: "प्रति घंटा",
  23: "एडॉन्स",
  24: "अवधि",
  25: "इस सेवा में अधिक समय लग सकता है",
  26: "मिनट",
  27: "गोपनीयता नीति",
  28: "हमारे बारे में",
  29: "नियम और शर्तें",
  30: "खोज सेवा",
  31: "खोज",
  32: "स्वागत है। जारी रखने के लिए कृपया लॉगिन करें",
  33: "ईमेल",
  34: "पासवर्ड",
  35: "मुझे याद करो",
  36: "साइन इन करें",
  37: "उपयोगकर्ता नाम या पासवर्ड गलत है",
  38: "अनुमति अस्वीकृत",
  39: "पासवर्ड भूल गए?",
  40: "साइन आउट",
  41: "या जारी रखें",
  42: "पासवर्ड रीसेट करें",
  43: "ईमेल",
  44: "नया पासवर्ड भेजें",
  45: "रीसेट पासवर्ड ईमेल भेजा गया। कृपया अपना मेल जांचें।",
  46: "लॉगिन पर वापस",
  47: "वापस जाओ",
  48: "खाता नहीं है। रजिस्टर करें",
  49: "रजिस्टर",
  50: "एक मिनट से भी कम समय में",
  51: "नाम",
  52: "पासवर्ड की पुष्टि करें",
  53: "उपयोगकर्ता नहीं बनाते",
  54: "कृपया ईमेल दर्ज करें",
  55: "कृपया पासवर्ड दर्ज करें",
  56: "पासवर्ड समान नहीं हैं",
  57: "ईमेल गलत हैं",
  58: "पता चुनें",
  59: "सत्यापन",
  60: "फोन नंबर",
  61: "हम सत्यापन कोड भेजेंगे।",
  62: "जारी रखें",
  63: "अपना फोन नंबर दर्ज करें",
  64: "कोड दर्ज करें",
  65: "हमने 6 अंकों का सत्यापन कोड भेजा है।",
  66: "वर्तमान पता",
  67: "अन्य पते",
  68: "पता नहीं मिला",
  69: "पता जोड़ें",
  70: "अपने आस-पास की सेवाओं का पता लगाएं",
  71: "लोकेशन एक्सेस की अनुमति देकर, आप अपने आस-पास की सेवाओं और प्रदाताओं की खोज कर सकते हैं।",
  72: "करंट लोकेशन का उपयोग करें",
  73: "मानचित्र से सेट करें",
  74: "अक्षांश",
  75: "देशांतर",
  76: "यहाँ उठाओ",
  77: "कृपया पता दर्ज करें",
  78: "स्थान जोड़ें",
  79: "लेबल के रूप में",
  80: "होम",
  81: "डिलीवरी पता",
  82: "कार्यालय",
  83: "अन्य",
  84: "संपर्क नाम",
  85: "फोन नंबर से संपर्क करें",
  86: "स्थान सहेजें",
  87: "कृपया नाम दर्ज करें",
  88: "कृपया फोन दर्ज करें",
  89: "इस सेवा को बुक करें",
  90: "आपका पता",
  91: "नया जोड़ें",
  92: "आपका पता प्रदाता कार्य क्षेत्र के बाहर है",
  93: "विवरण देखें",
  94: "विशेष अनुरोध",
  95: "किसी भी समय",
  96: "एक आदेश निर्धारित करें",
  97: "एक तिथि और समय चुनें",
  98: "अनुरोधित सेवा चालू",
  99: "बंद करें",
  100: "कृपया पता चुनें",
  101: "कूपन कोड",
  102: "कूपन नहीं मिला",
  103: "कूपन समाप्त हो गया है",
  104: "कूपन इस प्रदाता द्वारा समर्थित नहीं है",
  105: "कूपन इस श्रेणी का समर्थन नहीं करता",
  106: "कूपन इस सेवा का समर्थन नहीं करता",
  107: "कूपन सक्रिय",
  108: "मात्रा",
  109: "मूल्य निर्धारण",
  110: "कूपन",
  111: "नहीं",
  112: "कर राशि",
  113: "कुल",
  114: "अनुरोधित सेवा चालू",
  115: "नकद भुगतान",
  116: "अभी पुष्टि करें और बुकिंग करें",
  117: "उपयोगकर्ता से:",
  118: "नई बुकिंग आ गई",
  119: "धन्यवाद!",
  120:
      "आपकी बुकिंग सफलतापूर्वक सबमिट कर दी गई है, आपको जल्द ही एक पुष्टिकरण प्राप्त होगा।",
  121: "ठीक है",
  122: "कृपया वैध कोड दर्ज करें",
  123: "खाता",
  124: "बुकिंग",
  125: "प्रोफाइल",
  126: "पसंदीदा",
  127: "सूचनाएं",
  128: "मेरा पता",
  129: "सूचना नहीं मिली",
  130: "बचाओ",
  131: "डेटा सहेजा गया",
  132: "पासवर्ड बदलें",
  133: "नया पासवर्ड",
  134: "नए पासवर्ड की पुष्टि करें",
  135: "पासवर्ड बदलें",
  136: "पासवर्ड दर्ज करें",
  137: "पासवर्ड की पुष्टि करें दर्ज करें",
  138: "पासवर्ड समान नहीं हैं",
  139: "पासवर्ड बदल गया",
  140: "पसंदीदा नहीं मिला",
  141: "पूरा पता",
  142: "कृपया चयनित स्थान के लिए मानचित्र पर टैप करें",
  143: "नहीं मिला ,,,",
  144: "किसी भी समय",
  145: "कोड भेजा गया। कृपया सत्यापन कोड के लिए अपने फोन की जांच करें।",
  146: "आपका फ़ोन नंबर सत्यापित है। आप फ़ोन नंबर संपादित नहीं कर सकते",
  147: "अनुरोध किया गया",
  148: "व्यवस्थापक द्वारा",
  149: "प्रदाता द्वारा",
  150: "ग्राहक द्वारा",
  151: "अब स्थिति:",
  152: "बुकिंग की स्थिति बदली गई",
  153: "इस प्रदाता को रेट करें",
  154: "आईडी",
  155: "बुकिंग सूची पर वापस",
  156: "समय निर्माण",
  157: "बुकिंग आईडी",
  158: "इस सेवा को रेट करें",
  159: "इस सेवा को रेट करने के लिए सितारों पर क्लिक करें",
  160: "हमें इस सेवा के बारे में कुछ बताएं",
  161: "छवि जोड़ें",
  162: "",
  163: "समीक्षा सबमिट करें",
  164: "आप चित्र जोड़ सकते हैं",
  165: "कृपया टेक्स्ट दर्ज करें",
  166: "खोजें",
  167: "या",
  168: "फ़िल्टर",
  169: "क्रमबद्ध करें",
  170: "आरोही (ए-जेड)",
  171: "अवरोही (जेड-ए)",
  172: "आपके आस-पास",
  173: "सुदूर",
  174: "कीमत",
  175: "फ़िल्टर रीसेट करें",
  176: "फ़िल्टर लागू करें",
  177: "भुगतान रद्द!",
  178: "आपकी बुकिंग रद्द कर दी गई है, आप फिर से बुकिंग कर सकते हैं।",
  179: "लॉगिन",
  180: "वर्तमान",
  181: "सबटोटल",
  182: "छूट",
  183: "उपश्रेणी",
  184: "अवतार बदलें",
  185: "पसंदीदा प्रदाता",
  186: "अभी उपलब्ध नहीं है",
  187: "संबंधित उत्पाद",
  188: "और देखें",
  189: "प्रदाता द्वारा क्रमबद्ध करें",
  190: "नहीं चुनें",
  191: "सेवा, प्रदाता या उत्पाद खोजें",
  193: "उत्पाद",
  194: "कार्ट में जोड़ें",
  195: "स्टॉक में",
  196: "कुल राशि",
  197: "कृपया प्रकार चुनें",
  198: "कार्ट में जोड़ा गया उत्पाद",
  199: "यह उत्पाद पहले से ही कार्ट में है",
  200: "माई कार्ट",
  201: "चेकआउट के लिए आगे बढ़ें",
  202: "आपकी गाड़ी खाली है",
  203: "एडॉन्स:",
  204: "मात्रा",
  205: "आइटम की कीमत",
  206: "अन्य उत्पाद",
  207: "क्या कुछ और है",
  208: "वैट/टैक्स",
  209: "उत्पाद खोजें",
  210: "प्रदाता उत्पाद",
  211: "समीक्षा और रेटिंग",
  212: "इस प्रदाता के लिए अधिकतम खरीद राशि:",
  213: "इस प्रदाता के लिए न्यूनतम खरीद राशि:",
  214: "प्रोमो कोड",
  215: "निकालें",
  216: "प्रोमो जोड़ें",
  217: "प्रोमो नहीं मिला",
  218: "मेरे पुरस्कार",
  219: "कोड दर्ज करें",
  220: "विशेष पेशकश",
  221: "अभी उपयोग करें",
  222: "जब तक वैध",
  223: "कूपन इस उत्पाद का समर्थन नहीं करता",
  224: "कोड लागू करें",
  225: "आपका प्रोमो कोड",
};
